name: loginsample_app
description: A new Flutter application. (sample)

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter  
    
  
  carousel_slider: ^2.3.1
  search_widget: ^1.0.2
  swipebuttonflutter:
  flutter_animation_progress_bar: ^1.0.5
  dropdown_date_picker: ^0.0.3
  flutter_datetime_picker: ^1.2.5
  
  rflutter_alert: ^1.0.3
  flutter_uploader: ^1.2.0
  flutter_dropzone: ^1.0.9
  flutter_screenutil: ^3.2.0
  responsive_widgets: ^1.1.0
  flutter_inappwebview: ^4.0.0+4
  flutter_launcher_icons: ^0.8.1
  flutter_expanded_tile: ^0.2.1
  flutter_point_tab_bar: ^0.1.0
  circular_check_box: ^1.0.4
  percent_indicator: ^2.1.8
  splashscreen: ^1.3.4
  smooth_page_indicator: ^0.2.0
  fluttertoast: ^7.1.5
  http: ^0.12.2
  convert: ^2.1.1
  flutter_session: ^0.1.1
  country_list_pick: ^1.0.1+2
  file_picker: ^2.1.5+1


  
  

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  ios: true 
  image_path: images/rec248.png   
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/Logo2.png
    - images/bg4.jpg
    - images/cs.png
    - images/CC1.png
    - images/CC2.png
    - images/Group-6.png
    - images/payment-logo-1.png
    - images/paypal1.png
    - images/CT.png
    - images/CT2.png
    - images/CT3.png
    - images/REC7.png
    - images/calendar1.png
    - images/support1.png
    - images/jigsaws1.png
    - images/time1.png
    - images/fast1.png
    - images/discount1.png
    - images/Group.png
    - images/rec13.png
    - images/pc.png
    - images/rec250.png
    - images/CT5.png
    - images/rec248.png
    - images/rec247.png
    - images/rec21.png
    - images/pc.png
    - images/diploma.png
    - images/hourglass.png
    - images/phone1.png
    - images/tag.png
    - images/rec21.png
    - images/world1.png
    - images/clock.png
    - images/Rectangle 10.png
    - images/student-avatar-male.png
    - images/wifi.png
    - images/rec260.jpg
    - images/rec261.jpg
    - images/rec262.jpg
    - images/rec263.jpg
    - images/rec264.jpg
    - images/check.png
    - images/rec3.png
    - images/rec1.jpg
    - images/rec2.jpg
    - images/wb.png
    - images/check1.png
    

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Circular STD
      fonts:
       - asset: fonts/Circular_std_bold.ttf
         style: normal
       - asset: fonts/Circular_std_book.ttf
         style: normal
          